app/models/__init__.py
from app.models.category import Category
from app.models.post import Post

app/models/category.py
from app import db

# Modelo Categoría
class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)

app/models/post.py
from app import db

# Modelo Post
class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=True)
    category = db.relationship('Category', backref=db.backref('posts', lazy=True))

app/__init__.py
import os
from flask import Flask, request, jsonify, render_template, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

from dotenv import load_dotenv 

#Cargar las variables de entorno
load_dotenv()

#crear instancia
app =  Flask(__name__)

# Configuración de la base de datos PostgreSQL
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

#Importar los modelos
from app.models import Category
from app.models import Post

#Importar las rutas
from app.routes.category import categories_bp
from app.routes.post import posts_bp

app.register_blueprint(categories_bp, url_prefix='/categories')
app.register_blueprint(posts_bp, url_prefix='/posts')

#Ruta Raiz
@app.route('/')
def index():
    return render_template('home.html')

app/routes/category.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from app.models import Category

categories_bp = Blueprint('categories', __name__)

# Ruta para ver todas las categorías
@categories_bp.route('/')
def listar_categorias():
    categorias = Category.query.all()
    return render_template('categories/listar_categorias.html', categories=categorias)

#Ruta /categories crear una nueva categoría
@categories_bp.route('/new', methods=['GET','POST'])
def add_category():
    if request.method == 'POST':
        name = request.form['nombre']
        new_category = Category(name=name)
        db.session.add(new_category)
        db.session.commit()

        return redirect(url_for('categories.listar_categorias'))
    
    #Aqui sigue si es GET
    return render_template('categories/create_category.html')

#Actualizar categoria
@categories_bp.route('/update/<int:id>', methods=['GET','POST'])
def update_category(id):
    category = Category.query.get(id)
    if request.method == 'POST':
        category.name = request.form['nombre']
        db.session.commit()
        return redirect(url_for('categories.listar_categorias'))
    
    return render_template('categories/update_category.html', category=category)

#Eliminar categoria
@categories_bp.route('/delete/<int:id>')
def delete_category(id):
    category = Category.query.get(id)
    if category:
        db.session.delete(category)
        db.session.commit()
    return redirect(url_for('categories.listar_categorias'))

app/routes/post.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from app.models import Post, Category

posts_bp = Blueprint('posts', __name__)

# Ruta para ver todos los posts
@posts_bp.route('/')
def listar_posts():
    posts = Post.query.all()
    categories = Category.query.all()
    return render_template('posts/listar_posts.html', posts=posts, categories=categories)

#Ruta /post crear un nuevo post
@posts_bp.route('/new', methods=['GET','POST'])
def add_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        category_id = request.form.get('category_id')
        new_post = Post(title=title, content=content, category_id=category_id)
        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for('posts.listar_posts'))
    
    #Aqui sigue si es GET
    categories = Category.query.all()
    return render_template('posts/create_post.html', categories=categories)

#Actualizar post
@posts_bp.route('/update/<int:id>', methods=['GET','POST'])
def update_post(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.title = request.form['title']
        post.category_id = request.form['category_id']
        post.content = request.form['content']
        db.session.commit()
        return redirect(url_for('posts.listar_posts'))
    
    categories = Category.query.all()
    return render_template('posts/update_post.html', post=post, categories=categories)

#Eliminar post
@posts_bp.route('/delete/<int:id>')
def delete_post(id):
    post = Post.query.get(id)
    if post:
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('posts.listar_posts'))

app/templates/base.html
<!DOCTYPE html>
<html class="theme-light" style="background-color: gainsboro;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ee9903c79f.js" crossorigin="anonymous"></script>
</head>
  <body >
    <header>
        <br>
        <h1 class="title has-text-centered is-1">Blog de Noticias</h1>
        <h2 class="subtitle has-text-centered is-4">Lo más reciente en México</h2>
        <div class="has-text-centered">
          <a  href="{{ url_for('index') }}" class="button is-success">Menú Principal</a>
        </div>
        <hr>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

app/templates/categories/create_category.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Categoría</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('categories.add_category') }}" method="post">
                        <div class="field">
                            <label class="label">Nombre:</label>
                            <div class="control">
                                <input class="input" type="text" name='nombre'>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('categories.listar_categorias') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/categories/listar_categorias.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <a  href="{{ url_for('categories.add_category') }}" class="button is-success"><i class="fa-solid fa-plus"></i> &nbsp; Agregar Categoría</a>
        <br><br>        
        {% for category in categories %}
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{ category.name }}</p>
                    </div>
                </div>
                <div class="content">
                </div>
                <a href="{{ url_for('categories.update_category', id = category.id )}}" class="button is-small is-link is-outlined"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="{{ url_for('categories.delete_category', id = category.id )}}" class="button is-small is-danger is-outlined"><i class="fa-solid fa-trash"></i></a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/categories/update_category.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Actualizar Categoría</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('categories.update_category', id = category.id) }}" method="post">
                        <div class="field">
                            <label class="label">Nombre:</label>
                            <div class="control">
                                <input class="input" type="text" name='nombre' value="{{category.name}}">
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('categories.listar_categorias') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/create_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('add_post') }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title'>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content"></textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('index') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/home.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}

<div class="container">
    <div class="columns">
        <div class="column is-10 is-offset-1">
            <br>
            <div class="box">
                <h1 class="title is-6">Panel principal</h1>
                <!--Arear para el acceso a los diferentes modulos -->
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <p class="title is-6"><i class="fa-solid fa-address-card"></i> &nbsp Administrar Noticias</p>
                            <p class="subtitle is-6">Crear, modificar, eliminar</p>
                            <a class="button is-info" href="{{ url_for('posts.listar_posts') }}" >Acceder&nbsp<i class="fa-solid fa-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="column">
                        <div class="box">
                            <p class="title is-6"><i class="fa-solid fa-address-card"></i> &nbsp Administrar Categorias</p>
                            <p class="subtitle is-6">Crear, modificar, eliminar</p>
                            <a class="button is-info" href="{{url_for('categories.listar_categorias')}}">Acceder&nbsp<i class="fa-solid fa-arrow-right"></i></a>
                        </div>
                    </div>
                    
                </div>
               


            </div>





        </div>
    </div>

</div>


{% endblock%}

app/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('posts.add_post') }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title'>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content"></textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('posts.listar_posts') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/posts/listar_posts.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <a  href="{{ url_for('posts.add_post') }}" class="button is-success"><i class="fa-solid fa-plus"></i> &nbsp; Agregar noticia</a>
        <br><br>        
        {% for post in posts %}
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{ post.title }}</p>
                        <p class="subtitle is-5">{{ post.category.name }}</p>
                    </div>
                </div>
                <div class="content">
                    {{ post.content }}
                </div>
                <a href="{{ url_for('posts.update_post', id = post.id )}}" class="button is-small is-link is-outlined"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="{{ url_for('posts.delete_post', id = post.id )}}" class="button is-small is-danger is-outlined"><i class="fa-solid fa-trash"></i></a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('posts.update_post', id = post.id) }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title' value="{{post.title}}">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}" {% if category.id == post.category_id %}selected{% endif %}>
                                            {{ category.name }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content" >{{post.content}}</textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('posts.listar_posts') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/update_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('update_post', id = post.id) }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title' value="{{post.title}}">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}" {% if category.id == post.category_id %}selected{% endif %}>
                                            {{ category.name }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content" >{{post.content}}</textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('index') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}